### PR TITLE
Added translatable="false" to several strings

### PR DESCRIPTION
**Pull request by yarons**
These strings were not marked as not needing translation, added the correct argument for these.

### CODE REVIEW

**Comment by velitasali** [comment]
Hey thanks for the help. I would like to merge it immediately, but there are already translated languages. Merging will make the strings that are now marked untranslatable obsolete. Also I believe separating strings for different contexts is giving translators flexibility. 

I would like to your thoughts on this. Maybe we can change way this works.

Thanks.

**Comment by yarons** [comment]
Hey it doesn't sound like a problem since these were not supposed to be translated in the first place.

**Comment by velitasali** [comment]
Actually it is up to the contributor to make use of this like mentioned here https://github.com/genonbeta/TrebleShot/wiki/Language-contribution#butn_ . Previously, I started to keep these untranslatabl becyase someone on the community requested these to be not used. I think it is great for future-proofing, but also a little extra work. 

If you think these are not necessary then we can agree on removing.

**Comment by yarons** [comment]
I guess these can be used as a comment but not as a translatable string, even if I'll translate it this string won't appear anywhere, this is the resource in layout.xml which is connected to strings.xml.

**Pull request merged**
