### PR TITLE
Problem: There is no Image sharing

### PR DESCRIPTION
**Pull request by gabm**
solution: add a simple image picker and sharing feature for images

While I admit that the picker could be improved (multi-column, folders etc.), this adds basic sharing features for images...

### CODE REVIEW

**Comment by gabm** [comment]
I got some merge conflicts with the iml files that got changed by android studio.. I checked again and I think they should be removed over all... 

... can you provide a icon for the image sharing functionality (currently its using the video sharing icon)

**Comment by velitasali** [comment]
Hey, thank you for your contribution. 

Image sharing functionality inside the app would be great but the reason why I was not implementing it was that I was hoping to find a better solution for checking items which I just today have completed coding the base structure with success. I was also thinking of merging videos and images section to provide a better UX. So, although I can merge this, when it is released it will not be the same. If we can work on this I would be happy :) . Again thank you for your work. Please let me know what you think.

**Comment by gabm** [comment]
Hey @velitasali,

well... My personal opinion on this is that its more important to deliver functionality and improve on that later on in small steps. While I understand that one doesn't want to release "non-perfect" code, i personally think its more important to get things out into the world fast...

With that in mind I coded that PR, just to get the image sharing functionality i was wishing for. I know its not perfect but it works and thats what is most important. If you have a better approach, then go ahead. I'm not upset if you don't accept the PR because you got something better in mind - or if you want to change my PR or my code. After all that is what drives open source forward and is good for everybody. On the other hand I would not like it if you just rejected my PR because its not _perfect_ and then take another half a year to provide a better solution. That just delays features and makes the app les useful (for me)...

Of course, you are the maintainer and you decide what you'd like to do...

**Comment by velitasali** [comment]
hi again @gabm. I am sorry if what I said bothered you. I should say that I'm not a native English speaker and some of my words may offend although they are not intentional. What I was trying to say was I was already planning to improve the sharing section to allow people share different type of items in different categories at the same time. So as you may have realized the current way of selecting files does not work when user tries to do a search or when he goes upper in file explorer etc. It was one of the issues. Another thing was I have to use RecyclerView to provide grid view which does not compatible with ListAdapter which TrebleShot currently relies on. And your code is totally agreeable and I tried to ask you if we could work on this together.

**Comment by gabm** [comment]
>  I am sorry if what I said bothered you. I should say that I'm not a native English speaker and some of my words may offend although they are not intentional. 

I am not at all offended by what you said! No worries...

What about merging this and then adding your improvements?

**Pull request merged**
